import {
  QUESTIONS,
  CATEGORIES,
  CATEGORY_MAX,
  TOTAL_MAX,
  getCategoryScore,
  getResultBand,
} from '@/app/lib/quiz-data'
import { generateAiReport } from '@/app/lib/mistral'

// TODO: durch den echten Firmennamen ersetzen, sobald der feststeht.
const COMPANY_NAME_PLACEHOLDER = '[Dein Firmenname]'

function buildPrompt(answers: (number | string)[]): string {
  const total = answers.reduce<number>(
    (sum, a) => sum + (typeof a === 'number' && a >= 0 ? a : 0),
    0
  )
  const band = getResultBand(total)

  const categoryLines = CATEGORIES.map((cat) => {
    const score = getCategoryScore(answers, cat)
    return `- ${cat}: ${score}/${CATEGORY_MAX[cat]}`
  }).join('\n')

  const textAnswers = QUESTIONS.filter((q) => q.type === 'text')
    .map((q) => {
      const answer = answers[q.id - 1]
      const value =
        typeof answer === 'string' && answer.trim() ? answer.trim() : '(keine Angabe)'
      return `Frage: "${q.text}"\nAntwort: "${value}"`
    })
    .join('\n\n')

  return `Du bist ein erfahrener KI-Strategieberater für kleine und mittlere Unternehmen. Ein Unternehmen hat gerade einen KI-Readiness-Check ausgefüllt. Schreibe einen personalisierten, konkreten Report auf Deutsch — direkt einsteigen, keine Anrede wie "Hallo" oder "Liebes Team".

GESAMTERGEBNIS: ${total}/${TOTAL_MAX} Punkte — Einstufung: "${band.label}"

SCORES PRO KATEGORIE:
${categoryLines}

DIE OFFENEN ANTWORTEN DES UNTERNEHMENS:
${textAnswers}

DEINE AUFGABE:
Schreibe einen Report mit zwei Abschnitten:

1. "Einschätzung" (2-3 Sätze): Wo steht das Unternehmen? Beziehe dich konkret auf das, was in den offenen Antworten oben steht — nicht generisch.

2. "Konkrete nächste Schritte" (3-4 Punkte als Liste): Gehe explizit auf die genannte Herausforderung, Branche/Teamgröße und den gewünschten Verbesserungsbereich aus den offenen Antworten ein. Jeder Punkt soll umsetzbar und spezifisch sein, kein Allgemeinplatz.

Ton: professionell, direkt, auf Deutsch, keine Floskeln, keine Wiederholung der Fragen, kein Abschlusssatz oder Call-to-Action (das ergänzen wir separat). Maximal 220 Wörter.`
}

/**
 * Fixed, deterministic closing pitch — intentionally NOT generated by the
 * model. An LLM asked to write a hard sales CTA tends to soften the wording
 * on regeneration; this guarantees the exact tone and placeholder every time.
 */
function buildClosingCta(): string {
  return `\n\n---\n\nWir helfen Unternehmen wie deinem dabei, KI strategisch und praktisch einzusetzen — von der Strategie bis zur Umsetzung.\n\n**Vereinbare jetzt dein kostenloses Erstgespräch mit ${COMPANY_NAME_PLACEHOLDER}.**`
}

export async function generateReport(answers: (number | string)[]): Promise<string> {
  const prompt = buildPrompt(answers)
  const body = await generateAiReport(prompt)
  return `${body}${buildClosingCta()}`
}
